version: 2
jobs:
    build:
        machine: true
        steps:
            - checkout
            - run: chmod +x bootstrap.sh
            - run: ./bootstrap.sh
            - run: docker build --build-arg N_PROC=$(nproc) -t anishitani/docker-qt 5.7.1
            - run: docker build --build-arg N_PROC=$(nproc) -t anishitani/docker-qt 5.8.0
            - run: docker build --build-arg N_PROC=$(nproc) -t anishitani/docker-qt 5.9.3
            - run: docker images
