defaults: &workdir
  working_directory: ~/workspace
  machine: true

version: 2

jobs:
  checkout:
    <<: *workdir
    steps:
      - checkout
      - run: pip install Jinja2
      - run: python bootstrap.py
      - persist_to_workspace:
          root: .
          paths:
            - 4.5.3
            - 4.8.6
            - 5.7.1
            - 5.8.0
            - 5.9.3
  build_453:
    <<: *workdir
    steps:
      - attach_workspace:
          at: .
      - run: docker build --build-arg N_JOBS=$(nproc) -t anishitani/docker-qt:4.5.3 4.5.3
      - run: docker login -u $DOCKER_API_USER -p $DOCKER_API_KEY
      - run: docker push anishitani/docker-qt:4.5.3
  build_486:
      <<: *workdir
      steps:
        - attach_workspace:
            at: .
        - run: docker build --build-arg N_JOBS=$(nproc) -t anishitani/docker-qt:4.8.6 4.8.6
        - run: docker login -u $DOCKER_API_USER -p $DOCKER_API_KEY
        - run: docker push anishitani/docker-qt:4.8.6
  build_571:
      <<: *workdir
      steps:
        - attach_workspace:
            at: .
        - run: docker build --build-arg N_JOBS=$(nproc) -t anishitani/docker-qt:5.7.1 5.7.1
        - run: docker login -u $DOCKER_API_USER -p $DOCKER_API_KEY
        - run: docker push anishitani/docker-qt:5.7.1
  build_580:
      <<: *workdir
      steps:
        - attach_workspace:
            at: .
        - run: docker build --build-arg N_JOBS=$(nproc) -t anishitani/docker-qt:5.8.0 5.8.0
        - run: docker login -u $DOCKER_API_USER -p $DOCKER_API_KEY
        - run: docker push anishitani/docker-qt:5.8.0
  build_593:
      <<: *workdir
      steps:
        - attach_workspace:
            at: .
        - run: docker build --build-arg N_JOBS=$(nproc) -t anishitani/docker-qt:5.9.3 5.9.3
        - run: docker login -u $DOCKER_API_USER -p $DOCKER_API_KEY
        - run: docker push anishitani/docker-qt:5.9.3


workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - checkout
      - build_453:
          requires:
            - checkout
      - build_486:
          requires:
            - checkout
      - build_571:
          requires:
            - checkout
      - build_580:
          requires:
            - checkout
      - build_593:
          requires:
            - checkout
